### ISSUE TITLE
Error with the chart when adding filter 

### ISSUE THREAD

**Issue by SOSkr** [WebDataRocks/web-pivot-table#15]
When I try to add a filter to a report that has a chart, it shows me this error

webdatarocks.js:1030 Uncaught TypeError: Cannot read properties of undefined (reading '2')

I have reproduced the error here
https://codepen.io/soskr/pen/popVOMj

The error only occurs when I try to define the slice property on the chart

**Comment by solja484** [comment]
If you remove the `slice` property from `getData`, the chart will display the same slice as the grid. So, you can configure the slice in the report and don't need to copy it into the chart configs.

**Comment by SOSkr** [comment]
Yes, that is the temporary solution that I applied. But if I have more than one calculated field in the report, the graph always uses the first one, so I must order the one I want to use first and in case I want to more than one graphs, I must make reports for each one with the same data with diferent order for the calculated fields, which I think is not convenient.

I apologize for my english.

**Comment by solja484** [comment]
This is the known issue for WebDataRocks, which may be fixed in upcoming releases, but the exact date is currently unknown.

I can also advise you to check out [Flexmonster pivot](https://www.flexmonster.com/). This component is developed by the same team, and the issue with GoogleCharts is already solved in FM.
