### ISSUE TITLE
Blank page in Export PDF

### ISSUE THREAD

**Issue by Kamo1966** [WebDataRocks/web-pivot-table#19]
With version 1.4.7: 
I have some problems with export PDF
There is still the problem with header on second page generated (see my last issue of november 2022). 
There is also an empty page (the second page generated, again) if you create a pdf with only horizontal split pages.
If you create a 3x4 pages pdf there is a second wrong page that seems replicate value from fourth page. Generated PDF have 13 page! 

If you dont scroll untill the total row the width of column generated in PDF are wrong. See attached. If you scroll video untill total row and then generate PDF everything is ok.
Is there a javascript way to scroll untill the total row before sending export command? it's a workaround while waiting for a fix.

![2023-03-04 09_46_05-FatAnnoLineaCliente pdf - Adobe Acrobat Reader (64-bit)](https://user-images.githubusercontent.com/98221105/222886275-f9499436-bfc7-4b76-bb28-4ce8af8836b6.png)

**Comment by maksymkaD** [comment]
Hello, @Kamo1966

Thank you for reporting these issues.
The Webdatarocks 1.4.7 included fixes for the issue with the measure order with numeric captions and type definitions for integrations with charting libraries in the `webdatarocks.d.ts` file. The described PDF export issues will be fixed in future updates. 

As a workaround, we recommend using the `print()` method for exporting the grid:
```
const params = {
  header: "<div>##CURRENT-DATE##</div>",
  footer: "<div>##PAGE-NUMBER##</div>"
}
webdatarocks.print(params);
```
This method prints the content of the grid via the OS print manager.
